### ISSUE TITLE
[Potion Swords] Skeletons spread out when wither-ized, even into nearby blocks

### ISSUE THREAD

**Issue by AndanteDevs** [Gamemode4Dev/GM4_Datapacks#127] opened 2018-12-22 12:58 UTC
### Expected Behavior
The skeletons should just simply 'turn into' wither skeletons and not move.

### Current Behavior
This is an issue that affects wither skeleton skull farms. When you hit multiple skeletons with the relevant potion sword to turn them into wither skeletons, the newly-created wither skeletons will 'spurt' out, even into adjacent blocks.

### Possible Solution
Create a temporary no collision team, use the `Team` nbt tag while summoning the transformed wither skeletons and then remove them from that team.

### Steps to Reproduce
1. Summon multiple skeletons in one place.
2. Hit them holding a golden sword with a poison II potion in your inventory.
3. Watch them, unless it (rarely) doesn't happen, spurt out. If caged, they'll suffocate in the blocks.

### Environment
Multiplayer on GM4 PSV
All modules installed, of course.

**Comment by misode** [comment] 2018-12-22 13:19
Works as intended imo

**Comment by Bluefire-610** [comment] 2018-12-23 23:40
Whilst this is indeed unintended behavior, fixing this would require a huge framework for a very minor effect. I'm sorry to say that this won't be fixed.

**Closed by Bluefire-610** 2018-12-23 23:40 UTC
Labels: wontfix
