### ISSUE TITLE
Putting a dropless spawner into a minecart makes the mobs start dropping loot again

### ISSUE THREAD

**Issue by Insane96** [Gamemode4Dev/GM4_Datapacks#348] opened 2019-12-15 09:03 UTC
**Describe the bug**
Dangerous Dungeons and Towers add spawners that spawn mobs that drop nothing but when the spawner is put into a Minecart the mobs spawned will drop items like normal

**To Reproduce**
1. Find a Tower or a Dangerous Dungeon
2. Put one of the spawners into a minecart
3. Profit.

**Expected behavior**
Mobs spawned from Spawner Minecarts should drop nothing

**Fix**
I guess checking if the spawner has dropless mobs?

**Environment**
 - Minecraft version: 1.15.1 pre-1
 - Server version: SP
 - Installed Datapacks: Dangerous Dungeons, Tower Structures, Orbis and Spawner Minecarts (all for 1.14)
 - Installed Mods: Carpet and Mouse Wheelie

**Comment by BluePsychoRanger** [comment] 2019-12-15 09:06
That's already a known "feature." It's been used all over the Public Server to convert spawners to drop loot. It's technically intentional and it's not like it's free cuz you still have to fuel the minecart spawner.

**Comment by misode** [comment] 2019-12-15 10:15
This was intended in 1.13 but actually fixed in 1.14. So this is a valid bug.

**Comment by Bloo-dev** [comment] 2021-08-22 09:28
This will no longer be relevant in 1.17 and beyond as Spawner Minecarts will copy the full NBT of whitelisted spawners. See PR #619  for details.

**Closed** 2021-08-22 10:49 UTC
Labels: bug
